### ISSUE TITLE
pydantic errors

### ISSUE THREAD

**Issue by akovachev** [phileaton/tradier-python#1]
I'm getting the following error when trying to do ``get_balances`` on a cash acct:

```
>>> t.get_balances()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/tradier_python/tradier_api.py", line 80, in get_balances
    res = AccountsAPIResponse(**data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for AccountsAPIResponse
balances.margin
  Field required [type=missing, input_value={'option_short_value': 0,..., 'unsettled_funds': 0}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing
balances.pdt
  Field required [type=missing, input_value={'option_short_value': 0,..., 'unsettled_funds': 0}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing
```

**Comment by simonque** [comment]
Fixed in https://github.com/phileaton/tradier-python/commit/927380e703b81b83bac1f5f70c08fa8630db1dc3

**Comment by elarchet** [comment]
I have a similar issue:

```python
  File "c:\Users\etien\OneDrive - Groupe ESSCA\Windows\Project-Kapital\backend\mylibs\tradier.py", line 31, in <module>
    a = t.get_quotes('AAPL')
        ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\etien\.virtualenvs\backend-qTsu2SEs\Lib\site-packages\tradier_python\tradier_api.py", line 391, in get_quotes
    res = MarketsAPIResponse(**ensure_list(data, "quotes"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\etien\.virtualenvs\backend-qTsu2SEs\Lib\site-packages\pydantic\main.py", line 193, in __init__   
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for MarketsAPIResponse
quotes.unmatched_symbols
        ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\etien\.virtualenvs\backend-qTsu2SEs\Lib\site-packages\tradier_python\tradier_api.py", line 391, in get_quotes
    res = MarketsAPIResponse(**ensure_list(data, "quotes"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\etien\.virtualenvs\backend-qTsu2SEs\Lib\site-packages\pydantic\main.py", line 193, in __init__   
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for MarketsAPIResponse
quotes.unmatched_symbols
  Field required [type=missing, input_value={'quote': [{'symbol': 'AA...root_symbols': 'AAPL'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
``` 

I am using tradier-python==0.1.3

**Comment by simonque** [comment]
The owner of tradier-python is not very active. Just keep a local copy of the code in your source code repo, it's only two files.

**Comment by phileaton** [comment]
I don’t have much use for the code or time to maintain it. I’d be happy to transfer ownership if somebody wants to take it over. Sent from my iPhoneOn Aug 9, 2024, at 12:10 PM, Simon Q ***@***.***> wrote:﻿
The owner of tradier-python is not very active. Just keep a local copy of the code in your source code repo, it's only two files.

**Comment by simonque** [comment]
I can take it over. Let me know what is required. e.g. how to publish to
the pypi project.

**Comment by phileaton** [comment]
Sorry for the delay. I can't transfer ownership to you because it says you already have a fork with the same name. I added you as a collaborator for now and we can decide how to proceed getting the ownership transfered to you. I will need your PyPi username to add you as an owner on PyPi.

**Comment by simonque** [comment]
Thanks. I'm currently occupied with other things right now. I'll get back
to you when I am done with that in a few weeks.
